name: LobbyCore
main: me.mralecroyt.LobbyCore.CoreMain
version: 1.0.4
authors: [MrAlecroYT, SMarc]
description: Plugin for LunaticMC Network
softpend: [PlaceholderAPI, Vault]
commands:
  setspawn:
    description: setea el Spawn
  memoria:
    description: Memoria
  lobbyreload:
    description: A reload
  donacion:
    description: Mensaje donacion
